//
//  GITUserActionViewController.h
//  GetItDone
//
//  Created by Amanda Jones on 3/27/14.
//  Copyright (c) 2014 Amanda Jones. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "GITManualTaskViewController.h"

/**
 This view controller displays a smart scheduling suggestion, and gives the user the actions he/she can take upon that suggestion. This view controller also handles the result of the user action taken.
 */
@interface GITUserActionViewController : UITableViewController <GITManualTaskDelegate>

/**
 Smart scheduling view controller to handle the smart scheduling
 */
@property (nonatomic, strong) GITSmartSchedulingViewController *smartScheduler;
/**
 The entity manager for task
 */
@property (nonatomic, strong) GITTaskManager *taskManager;
/**
 The dictionary passed in from the previous view control. Can include a task, task information inputted by the user, and a date suggestion generated by the smart scheduling view controller
 */
@property (nonatomic, strong) NSMutableDictionary *taskInfoDictionary;
/**
 The label that will display the smart scheduling suggestion for a task
 */
@property (strong, nonatomic) IBOutlet UILabel *labelSuggestion;
/**
 The date to be suggested for the task
 */
@property (strong, nonatomic) NSDate *dateSuggestion;
/**
 Formats dates. E.g. "Sept 6, 2013 1:00 PM"
 */
@property (nonatomic, strong) NSDateFormatter *formatter;

- (IBAction)buttonPressedAccept:(id)sender;

- (IBAction)buttonPressedReject:(id)sender;

- (IBAction)buttonPressedManuallySchedule:(id)sender;
@end
