//
//  GITUserActionViewController.h
//  GetItDone
//
//  Created by Amanda Jones on 3/27/14.
//  Copyright (c) 2014 Amanda Jones. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "GITManualTaskViewController.h"

@class GITUserActionViewController;

/**
 Defines the methods for the UserActionDelegate
 */
@protocol GITUserActionDelegate <NSObject>

/**
 Lets the delegate know that the user accepted the time suggested
 @param controller The GITUserActionViewController the user acted within
 @param task The task made with the accepted date suggestion
 */
-(void)userActionViewController:(GITUserActionViewController *)controller finishedWithAcceptForTask:(GITTask *)task;

/**
 Lets the delegate know that the user rejected the time suggested
 @param controller The GITUserActionViewController the user acted within
 @param title The task title inputted on the AddTaskVC
 @param categoryTitle The title of the task's category inputted on the AddTaskVC
 @param start The start time of the task inputted on the AddTaskVC
 @param duration The duration of the task inputted on the AddTaskVC
 */
-(void)userActionViewController:(GITUserActionViewController *)controller finishedWithRejectForTaskTitle:(NSString *)title categoryTitle:(NSString *)categoryTitle startTime:(NSDate *)start duration:(NSNumber *)duration;

@end

/**
 This view controller displays a smart scheduling suggestion, and gives the user the actions he/she can take upon that suggestion. This view controller also handles the result of the user action taken.
 */
@interface GITUserActionViewController : UITableViewController <GITManualTaskDelegate>

/**
 Delegate for UserActionVC
 */
@property (nonatomic) id<GITUserActionDelegate> delegate;
/**
 The entity manager for task
 */
@property (nonatomic, strong) GITTaskManager *taskManager;
/**
 The dictionary passed in from the previous view control. Can include a task, task information inputted by the user, and a date suggestion generated by the smart scheduling view controller
 */
@property (nonatomic, strong) NSMutableDictionary *taskInfoDictionary;
/**
 The button for "Cancel" was pressed
 */
- (IBAction)buttonPressedCancel:(id)sender;
/**
 The label that will display the smart scheduling suggestion for a task
 */
@property (strong, nonatomic) IBOutlet UILabel *labelSuggestion;
/**
 The date to be suggested for the task
 */
@property (strong, nonatomic) NSDate *dateSuggestion;
/**
 Formats dates. E.g. "Sept 6, 2013 1:00 PM"
 */
@property (nonatomic, strong) NSDateFormatter *formatter;
/**
 Flag so I know if a task is happening or not. If it's happening, it implies user go to this screen by postponing it. Therefore, want to force them to take some action on task
 */
@property (nonatomic) BOOL taskHappening;
/**
 The task current happening that an alert needs to be shown for
 */
@property (nonatomic, strong) GITTask *currentTask;

- (IBAction)buttonPressedAccept:(id)sender;

- (IBAction)buttonPressedReject:(id)sender;

- (IBAction)buttonPressedManuallySchedule:(id)sender;
@end
